using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using TermSnap.Models;

namespace TermSnap.Services;

/// <summary>
/// GSD (Get-Shit-Done) 워크플로우 서비스
/// .planning/ 폴더 구조 생성 및 관리
/// </summary>
public class GsdWorkflowService
{
    private const string PlanningFolder = ".planning";
    private const string ResearchFolder = "research";

    /// <summary>
    /// .planning/ 폴더가 존재하는지 확인
    /// </summary>
    public static bool HasPlanningFolder(string workingDirectory)
    {
        if (string.IsNullOrEmpty(workingDirectory))
            return false;

        var planningPath = Path.Combine(workingDirectory, PlanningFolder);
        return Directory.Exists(planningPath);
    }

    /// <summary>
    /// GSD 워크플로우 초기화 (.planning/ 폴더 및 템플릿 생성)
    /// </summary>
    public static async Task<bool> InitializeAsync(string workingDirectory, string projectName, string? projectDescription = null)
    {
        if (string.IsNullOrEmpty(workingDirectory))
            return false;

        try
        {
            var planningPath = Path.Combine(workingDirectory, PlanningFolder);
            var researchPath = Path.Combine(planningPath, ResearchFolder);

            // 폴더 생성
            Directory.CreateDirectory(planningPath);
            Directory.CreateDirectory(researchPath);

            // 기본 파일들 생성
            await CreateConfigAsync(planningPath, projectName);
            await CreateProjectMdAsync(planningPath, projectName, projectDescription);
            await CreateRoadmapMdAsync(planningPath, projectName);
            await CreateStateMdAsync(planningPath);
            await CreateRequirementsMdAsync(planningPath, projectName);

            return true;
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[GsdWorkflowService] Initialize failed: {ex.Message}");
            return false;
        }
    }

    /// <summary>
    /// config.json 생성
    /// </summary>
    private static async Task CreateConfigAsync(string planningPath, string projectName)
    {
        var config = new GsdConfig
        {
            ProjectName = projectName,
            CreatedAt = DateTime.Now,
            ExecutionMode = "interactive",
            PlanningDepth = "standard",
            GitTracking = true,
            ModelProfile = "balanced"
        };

        var json = JsonSerializer.Serialize(config, new JsonSerializerOptions { WriteIndented = true });
        await File.WriteAllTextAsync(Path.Combine(planningPath, "config.json"), json);
    }

    /// <summary>
    /// PROJECT.md 템플릿 생성
    /// </summary>
    private static async Task CreateProjectMdAsync(string planningPath, string projectName, string? description)
    {
        var template = $@"# {projectName}

## Overview

{description ?? "프로젝트 설명을 입력하세요."}

## Goals

- [ ] 목표 1
- [ ] 목표 2
- [ ] 목표 3

## Tech Stack

- **Frontend**:
- **Backend**:
- **Database**:
- **Infrastructure**:

## Key Decisions

| Decision | Rationale | Date |
|----------|-----------|------|
| | | |

## Constraints

- 제약 사항 1
- 제약 사항 2

## Out of Scope

- 범위 밖 항목 1
- 범위 밖 항목 2

---

*Generated by TermSnap GSD Workflow*
*Created: {DateTime.Now:yyyy-MM-dd HH:mm}*
";

        await File.WriteAllTextAsync(Path.Combine(planningPath, "PROJECT.md"), template, Encoding.UTF8);
    }

    /// <summary>
    /// ROADMAP.md 템플릿 생성
    /// </summary>
    private static async Task CreateRoadmapMdAsync(string planningPath, string projectName)
    {
        var template = $@"# {projectName} - Roadmap

## Progress Overview

| Phase | Name | Status | Progress |
|-------|------|--------|----------|
| 1 | Setup & Foundation | 🔵 Pending | 0% |
| 2 | Core Features | ⚪ Pending | 0% |
| 3 | Integration & Testing | ⚪ Pending | 0% |
| 4 | Polish & Deploy | ⚪ Pending | 0% |

---

## Phase 1: Setup & Foundation

### Objectives
- [ ] 프로젝트 구조 설정
- [ ] 개발 환경 구성
- [ ] 기본 아키텍처 수립

### Success Criteria
- 프로젝트가 빌드되고 실행됨
- 기본 테스트가 통과함

### Status: 🔵 In Progress

---

## Phase 2: Core Features

### Objectives
- [ ] 핵심 기능 1 구현
- [ ] 핵심 기능 2 구현

### Success Criteria
- 핵심 기능이 동작함
- 단위 테스트 통과

### Status: ⚪ Pending

---

## Phase 3: Integration & Testing

### Objectives
- [ ] 통합 테스트
- [ ] E2E 테스트
- [ ] 버그 수정

### Success Criteria
- 모든 테스트 통과
- 주요 버그 없음

### Status: ⚪ Pending

---

## Phase 4: Polish & Deploy

### Objectives
- [ ] UI/UX 개선
- [ ] 성능 최적화
- [ ] 배포

### Success Criteria
- 프로덕션 배포 완료
- 문서화 완료

### Status: ⚪ Pending

---

*Generated by TermSnap GSD Workflow*
*Last Updated: {DateTime.Now:yyyy-MM-dd HH:mm}*
";

        await File.WriteAllTextAsync(Path.Combine(planningPath, "ROADMAP.md"), template, Encoding.UTF8);
    }

    /// <summary>
    /// STATE.md 템플릿 생성
    /// </summary>
    private static async Task CreateStateMdAsync(string planningPath)
    {
        var template = $@"# Project State

## Current Position

- **Phase**: 1
- **Step**: discuss
- **Last Updated**: {DateTime.Now:yyyy-MM-dd HH:mm}

## Recent Activity

| Date | Phase | Action | Result |
|------|-------|--------|--------|
| {DateTime.Now:yyyy-MM-dd} | 0 | Project initialized | ✅ |

## Context for Next Session

> 다음 세션에서 이어서 진행할 내용을 여기에 기록하세요.

## Blockers

- (없음)

## Notes

- 프로젝트가 초기화되었습니다.
- `/gsd:discuss-phase 1`으로 첫 번째 페이즈를 시작하세요.

---

*Generated by TermSnap GSD Workflow*
";

        await File.WriteAllTextAsync(Path.Combine(planningPath, "STATE.md"), template, Encoding.UTF8);
    }

    /// <summary>
    /// REQUIREMENTS.md 템플릿 생성
    /// </summary>
    private static async Task CreateRequirementsMdAsync(string planningPath, string projectName)
    {
        var template = $@"# {projectName} - Requirements

## v1.0 (MVP)

### Must Have

| ID | Category | Requirement | Status |
|----|----------|-------------|--------|
| REQ-001 | Core | 핵심 기능 1 | ⚪ |
| REQ-002 | Core | 핵심 기능 2 | ⚪ |
| REQ-003 | UI | 기본 UI | ⚪ |

### Should Have

| ID | Category | Requirement | Status |
|----|----------|-------------|--------|
| REQ-101 | UX | 사용자 경험 개선 | ⚪ |

## v2.0 (Future)

| ID | Category | Requirement | Notes |
|----|----------|-------------|-------|
| REQ-201 | Feature | 추가 기능 | 후속 버전 |

## Out of Scope

- 범위 밖 항목 1
- 범위 밖 항목 2

---

### Status Legend

- ⚪ Pending
- 🔵 In Progress
- ✅ Complete
- ❌ Blocked
- ⏸️ Deferred

---

*Generated by TermSnap GSD Workflow*
*Last Updated: {DateTime.Now:yyyy-MM-dd HH:mm}*
";

        await File.WriteAllTextAsync(Path.Combine(planningPath, "REQUIREMENTS.md"), template, Encoding.UTF8);
    }

    /// <summary>
    /// Phase Context 파일 생성 (discuss 단계)
    /// </summary>
    public static async Task CreatePhaseContextAsync(string workingDirectory, int phaseNumber, string context)
    {
        var planningPath = Path.Combine(workingDirectory, PlanningFolder);
        var fileName = $"phase-{phaseNumber}-CONTEXT.md";

        var template = $@"# Phase {phaseNumber} - Context

## Discussion Summary

{context}

## Decisions Made

| Topic | Decision | Rationale |
|-------|----------|-----------|
| | | |

## Gray Areas Resolved

-

## Deferred to Later Phases

-

---

*Created: {DateTime.Now:yyyy-MM-dd HH:mm}*
";

        await File.WriteAllTextAsync(Path.Combine(planningPath, fileName), template, Encoding.UTF8);
    }

    /// <summary>
    /// Phase Plan 파일 생성 (plan 단계)
    /// </summary>
    public static async Task CreatePhasePlanAsync(string workingDirectory, int phaseNumber, int planNumber, string planContent)
    {
        var planningPath = Path.Combine(workingDirectory, PlanningFolder);
        var fileName = $"phase-{phaseNumber}-{planNumber}-PLAN.md";

        var template = $@"# Phase {phaseNumber} - Plan {planNumber}

## Objective

{planContent}

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

## Files to Modify

| File | Action | Description |
|------|--------|-------------|
| | | |

## Dependencies

- (없음)

## Verification

- [ ] 빌드 성공
- [ ] 테스트 통과
- [ ] 기능 동작 확인

## Success Criteria

-

---

*Created: {DateTime.Now:yyyy-MM-dd HH:mm}*
";

        await File.WriteAllTextAsync(Path.Combine(planningPath, fileName), template, Encoding.UTF8);
    }

    /// <summary>
    /// Phase Summary 파일 생성 (execute 완료 후)
    /// </summary>
    public static async Task CreatePhaseSummaryAsync(string workingDirectory, int phaseNumber, int planNumber, string summary)
    {
        var planningPath = Path.Combine(workingDirectory, PlanningFolder);
        var fileName = $"phase-{phaseNumber}-{planNumber}-SUMMARY.md";

        var template = $@"# Phase {phaseNumber} - Plan {planNumber} Summary

## Execution Result

{summary}

## Changes Made

| File | Change Type | Description |
|------|-------------|-------------|
| | | |

## Commits

| Hash | Message |
|------|---------|
| | |

## Issues Encountered

- (없음)

## Time Spent

- Start:
- End:
- Duration:

---

*Created: {DateTime.Now:yyyy-MM-dd HH:mm}*
";

        await File.WriteAllTextAsync(Path.Combine(planningPath, fileName), template, Encoding.UTF8);
    }

    /// <summary>
    /// Phase UAT 파일 생성 (verify 단계)
    /// </summary>
    public static async Task CreatePhaseUatAsync(string workingDirectory, int phaseNumber, string verificationResult)
    {
        var planningPath = Path.Combine(workingDirectory, PlanningFolder);
        var fileName = $"phase-{phaseNumber}-UAT.md";

        var template = $@"# Phase {phaseNumber} - User Acceptance Test

## Verification Status: ⏳ Pending

## Observable Truths

| Truth | Status | Evidence |
|-------|--------|----------|
| | | |

## Artifacts Check

| Artifact | Exists | Substantial | Connected |
|----------|--------|-------------|-----------|
| | | | |

## Key Links Verified

| From | To | Status |
|------|----|--------|
| | | |

## Gaps Found

{verificationResult}

## Human Verification Needed

- [ ]

## Result

- **Status**: pending | passed | gaps_found | human_needed
- **Next Action**:

---

*Created: {DateTime.Now:yyyy-MM-dd HH:mm}*
";

        await File.WriteAllTextAsync(Path.Combine(planningPath, fileName), template, Encoding.UTF8);
    }

    /// <summary>
    /// STATE.md 업데이트
    /// </summary>
    public static async Task UpdateStateAsync(string workingDirectory, int phase, string step, string? note = null)
    {
        var planningPath = Path.Combine(workingDirectory, PlanningFolder);
        var statePath = Path.Combine(planningPath, "STATE.md");

        if (!File.Exists(statePath))
            return;

        var content = await File.ReadAllTextAsync(statePath);

        // Phase, Step 업데이트
        content = System.Text.RegularExpressions.Regex.Replace(
            content,
            @"\*\*Phase\*\*: \d+",
            $"**Phase**: {phase}");

        content = System.Text.RegularExpressions.Regex.Replace(
            content,
            @"\*\*Step\*\*: \w+",
            $"**Step**: {step}");

        content = System.Text.RegularExpressions.Regex.Replace(
            content,
            @"\*\*Last Updated\*\*: .+",
            $"**Last Updated**: {DateTime.Now:yyyy-MM-dd HH:mm}");

        await File.WriteAllTextAsync(statePath, content, Encoding.UTF8);
    }

    /// <summary>
    /// 현재 GSD 상태 읽기
    /// </summary>
    public static GsdConfig? LoadConfig(string workingDirectory)
    {
        try
        {
            var configPath = Path.Combine(workingDirectory, PlanningFolder, "config.json");
            if (!File.Exists(configPath))
                return null;

            var json = File.ReadAllText(configPath);
            return JsonSerializer.Deserialize<GsdConfig>(json);
        }
        catch
        {
            return null;
        }
    }

    /// <summary>
    /// GSD 진행 상황 요약
    /// </summary>
    public static string GetProgressSummary(string workingDirectory)
    {
        var planningPath = Path.Combine(workingDirectory, PlanningFolder);

        if (!Directory.Exists(planningPath))
            return "GSD 워크플로우가 초기화되지 않았습니다. `/ts:init`으로 시작하세요.";

        var config = LoadConfig(workingDirectory);
        if (config == null)
            return ".planning/ 폴더는 있지만 config.json을 읽을 수 없습니다.";

        var sb = new StringBuilder();
        sb.AppendLine($"# {config.ProjectName} - Progress");
        sb.AppendLine();
        sb.AppendLine($"- **Phase**: {config.CurrentPhase}");
        sb.AppendLine($"- **Step**: {config.CurrentStep}");
        sb.AppendLine($"- **Mode**: {config.ExecutionMode}");
        sb.AppendLine();

        // 존재하는 파일들 확인
        var files = Directory.GetFiles(planningPath, "*.md");
        sb.AppendLine("## Files");
        foreach (var file in files)
        {
            sb.AppendLine($"- {Path.GetFileName(file)}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// STATE.md에서 현재 상태 파싱
    /// </summary>
    public static GsdState? LoadState(string workingDirectory)
    {
        try
        {
            var statePath = Path.Combine(workingDirectory, PlanningFolder, "STATE.md");
            if (!File.Exists(statePath))
                return null;

            var content = File.ReadAllText(statePath);
            var state = new GsdState();

            // Phase 파싱: **Phase**: 1
            var phaseMatch = Regex.Match(content, @"\*\*Phase\*\*:\s*(\d+)");
            if (phaseMatch.Success)
                state.CurrentPhase = int.Parse(phaseMatch.Groups[1].Value);

            // Step 파싱: **Step**: discuss
            var stepMatch = Regex.Match(content, @"\*\*Step\*\*:\s*(\w+)");
            if (stepMatch.Success)
                state.CurrentStep = stepMatch.Groups[1].Value.ToLower();

            // Last Updated 파싱
            var updatedMatch = Regex.Match(content, @"\*\*Last Updated\*\*:\s*(.+)");
            if (updatedMatch.Success && DateTime.TryParse(updatedMatch.Groups[1].Value, out var dt))
                state.LastUpdated = dt;

            return state;
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[GsdWorkflowService] LoadState failed: {ex.Message}");
            return null;
        }
    }

    /// <summary>
    /// Phase 문서 목록 가져오기
    /// </summary>
    public static List<string> GetPhaseFiles(string workingDirectory, int phaseNumber)
    {
        var result = new List<string>();
        var planningPath = Path.Combine(workingDirectory, PlanningFolder);

        if (!Directory.Exists(planningPath))
            return result;

        var pattern = $"phase-{phaseNumber}-*.md";
        var files = Directory.GetFiles(planningPath, pattern);

        foreach (var file in files)
        {
            result.Add(Path.GetFileName(file));
        }

        return result;
    }

    /// <summary>
    /// Phase 문서 내용 읽기
    /// </summary>
    /// <param name="workingDirectory">작업 디렉토리</param>
    /// <param name="phaseNumber">Phase 번호</param>
    /// <param name="documentType">문서 유형 (CONTEXT, PLAN, SUMMARY, UAT)</param>
    /// <param name="planNumber">Plan 번호 (PLAN, SUMMARY인 경우)</param>
    public static async Task<string?> ReadPhaseDocumentAsync(
        string workingDirectory,
        int phaseNumber,
        string documentType,
        int planNumber = 1)
    {
        try
        {
            var planningPath = Path.Combine(workingDirectory, PlanningFolder);
            string fileName;

            switch (documentType.ToUpper())
            {
                case "CONTEXT":
                    fileName = $"phase-{phaseNumber}-CONTEXT.md";
                    break;
                case "PLAN":
                    fileName = $"phase-{phaseNumber}-{planNumber}-PLAN.md";
                    break;
                case "SUMMARY":
                    fileName = $"phase-{phaseNumber}-{planNumber}-SUMMARY.md";
                    break;
                case "UAT":
                    fileName = $"phase-{phaseNumber}-UAT.md";
                    break;
                default:
                    return null;
            }

            var filePath = Path.Combine(planningPath, fileName);
            if (!File.Exists(filePath))
                return null;

            return await File.ReadAllTextAsync(filePath);
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[GsdWorkflowService] ReadPhaseDocument failed: {ex.Message}");
            return null;
        }
    }

    /// <summary>
    /// Phase 문서 저장
    /// </summary>
    public static async Task<bool> SavePhaseDocumentAsync(
        string workingDirectory,
        int phaseNumber,
        string documentType,
        string content,
        int planNumber = 1)
    {
        try
        {
            var planningPath = Path.Combine(workingDirectory, PlanningFolder);
            string fileName;

            switch (documentType.ToUpper())
            {
                case "CONTEXT":
                    fileName = $"phase-{phaseNumber}-CONTEXT.md";
                    break;
                case "PLAN":
                    fileName = $"phase-{phaseNumber}-{planNumber}-PLAN.md";
                    break;
                case "SUMMARY":
                    fileName = $"phase-{phaseNumber}-{planNumber}-SUMMARY.md";
                    break;
                case "UAT":
                    fileName = $"phase-{phaseNumber}-UAT.md";
                    break;
                default:
                    return false;
            }

            var filePath = Path.Combine(planningPath, fileName);
            await File.WriteAllTextAsync(filePath, content, Encoding.UTF8);
            return true;
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[GsdWorkflowService] SavePhaseDocument failed: {ex.Message}");
            return false;
        }
    }

    /// <summary>
    /// Plan에서 태스크 목록 추출 ("- [ ] Task" 패턴)
    /// </summary>
    public static List<GsdTask> ExtractTasksFromPlan(string planContent)
    {
        var tasks = new List<GsdTask>();

        if (string.IsNullOrEmpty(planContent))
            return tasks;

        // - [ ] 또는 - [x] 패턴 검색
        var matches = Regex.Matches(planContent, @"^-\s*\[([ xX])\]\s*(.+)$", RegexOptions.Multiline);

        foreach (Match match in matches)
        {
            var isCompleted = match.Groups[1].Value.Trim().ToLower() == "x";
            var content = match.Groups[2].Value.Trim();

            tasks.Add(new GsdTask
            {
                Content = content,
                IsCompleted = isCompleted
            });
        }

        return tasks;
    }

    /// <summary>
    /// GsdStep 열거형을 문자열로 변환
    /// </summary>
    public static string StepToString(GsdStep step)
    {
        return step switch
        {
            GsdStep.Discuss => "discuss",
            GsdStep.Plan => "plan",
            GsdStep.Execute => "execute",
            GsdStep.Verify => "verify",
            _ => "discuss"
        };
    }

    /// <summary>
    /// 문자열을 GsdStep 열거형으로 변환
    /// </summary>
    public static GsdStep StringToStep(string step)
    {
        return step.ToLower() switch
        {
            "discuss" => GsdStep.Discuss,
            "plan" => GsdStep.Plan,
            "execute" => GsdStep.Execute,
            "verify" => GsdStep.Verify,
            _ => GsdStep.Discuss
        };
    }

    /// <summary>
    /// config.json 업데이트
    /// </summary>
    public static async Task UpdateConfigAsync(string workingDirectory, int phase, GsdStep step)
    {
        try
        {
            var config = LoadConfig(workingDirectory);
            if (config == null) return;

            config.CurrentPhase = phase;
            config.CurrentStep = StepToString(step);

            var configPath = Path.Combine(workingDirectory, PlanningFolder, "config.json");
            var json = JsonSerializer.Serialize(config, new JsonSerializerOptions { WriteIndented = true });
            await File.WriteAllTextAsync(configPath, json);

            // STATE.md도 업데이트
            await UpdateStateAsync(workingDirectory, phase, StepToString(step));
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[GsdWorkflowService] UpdateConfig failed: {ex.Message}");
        }
    }

    /// <summary>
    /// Plan 내용을 PRD 형식으로 변환 (Execute용)
    /// </summary>
    public static string ConvertPlanToPrd(string planContent, int phaseNumber)
    {
        if (string.IsNullOrEmpty(planContent))
            return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine($"# Phase {phaseNumber} Implementation");
        sb.AppendLine();
        sb.AppendLine("## Tasks from Plan");
        sb.AppendLine();
        sb.AppendLine(planContent);
        sb.AppendLine();
        sb.AppendLine("## Instructions");
        sb.AppendLine("- Implement each task marked with [ ]");
        sb.AppendLine("- Commit after completing each task");
        sb.AppendLine("- When all tasks are done, output: [RALPH_COMPLETE]");

        return sb.ToString();
    }

    /// <summary>
    /// Plan에서 AgentTask 목록 추출
    /// </summary>
    public static List<AgentTask> ExtractAgentTasksFromPlan(string planContent)
    {
        var agentTasks = new List<AgentTask>();
        var gsdTasks = ExtractTasksFromPlan(planContent);

        foreach (var task in gsdTasks)
        {
            agentTasks.Add(new AgentTask
            {
                Description = task.Content,
                Status = task.IsCompleted ? AgentTaskStatus.Completed : AgentTaskStatus.Pending
            });
        }

        return agentTasks;
    }

    /// <summary>
    /// 실행 모드를 config.json에 저장
    /// </summary>
    public static async Task UpdateExecutionModeAsync(string workingDirectory, ExecutionMode mode)
    {
        try
        {
            var config = LoadConfig(workingDirectory);
            if (config == null) return;

            config.ExecutionMode = mode switch
            {
                ExecutionMode.Interactive => "interactive",
                ExecutionMode.Yolo => "yolo",
                ExecutionMode.EcoMode => "eco",
                ExecutionMode.Pipeline => "pipeline",
                ExecutionMode.Swarm => "swarm",
                ExecutionMode.Expert => "expert",
                _ => "interactive"
            };

            var configPath = Path.Combine(workingDirectory, PlanningFolder, "config.json");
            var json = JsonSerializer.Serialize(config, new JsonSerializerOptions { WriteIndented = true });
            await File.WriteAllTextAsync(configPath, json);
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[GsdWorkflowService] UpdateExecutionMode failed: {ex.Message}");
        }
    }

    /// <summary>
    /// config.json에서 실행 모드 로드
    /// </summary>
    public static ExecutionMode LoadExecutionMode(string workingDirectory)
    {
        var config = LoadConfig(workingDirectory);
        if (config == null) return ExecutionMode.Interactive;

        return config.ExecutionMode?.ToLower() switch
        {
            "interactive" => ExecutionMode.Interactive,
            "yolo" => ExecutionMode.Yolo,
            "eco" => ExecutionMode.EcoMode,
            "pipeline" => ExecutionMode.Pipeline,
            "swarm" => ExecutionMode.Swarm,
            "expert" => ExecutionMode.Expert,
            _ => ExecutionMode.Interactive
        };
    }
}
