using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using TermSnap.Models;
using TermSnap.Services;

namespace TermSnap.Views;

/// <summary>
/// AI 장기기억 패널 코드비하인드 (MEMORY.md 기반)
/// 탭별로 독립적인 MemoryService 인스턴스를 가짐
/// </summary>
public partial class MemoryPanel : UserControl
{
    private readonly MemoryService _memoryService = new();
    private MemoryType? _currentTypeFilter = null;
    private List<MemoryDisplayItem> _allItems = new();

    /// <summary>
    /// 패널 닫기 요청
    /// </summary>
    public event EventHandler? CloseRequested;

    public MemoryPanel()
    {
        InitializeComponent();
        Loaded += MemoryPanel_Loaded;
    }

    private async void MemoryPanel_Loaded(object sender, RoutedEventArgs e)
    {
        await RefreshMemories();
    }

    /// <summary>
    /// 작업 디렉토리 설정
    /// </summary>
    public void SetWorkingDirectory(string directory)
    {
        _memoryService.SetWorkingDirectory(directory);
        _ = RefreshMemories();
    }

    /// <summary>
    /// 메모리 목록 새로고침
    /// </summary>
    public async Task RefreshMemories()
    {
        try
        {
            var memories = _memoryService.GetAllMemories();

            _allItems = memories.Select(m => new MemoryDisplayItem
            {
                Id = m.Id,
                Content = m.Content,
                Type = m.Type,
                TypeIcon = GetTypeIcon(m.Type),
                TypeName = GetTypeName(m.Type),
                Importance = m.Importance,
                ImportanceText = $"중요도 {(m.Importance * 100):0}%",
                Source = m.Source,
                HasSource = !string.IsNullOrEmpty(m.Source),
                AccessCount = m.AccessCount,
                AccessInfo = $"접근 {m.AccessCount}회",
                CreatedAt = m.CreatedAt,
                IsAutoGenerated = m.IsAutoGenerated
            }).ToList();

            ApplyFilter();
            UpdateStatistics();
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[MemoryPanel] 로드 실패: {ex.Message}");
        }

        await Task.CompletedTask;
    }

    /// <summary>
    /// 필터 적용
    /// </summary>
    private void ApplyFilter()
    {
        // 초기화 전에는 무시
        if (MemoryList == null || SearchBox == null) return;

        var filtered = _allItems.AsEnumerable();

        // 타입 필터
        if (_currentTypeFilter.HasValue)
        {
            filtered = filtered.Where(m => m.Type == _currentTypeFilter.Value);
        }

        // 검색어 필터
        var searchText = SearchBox.Text?.Trim();
        if (!string.IsNullOrEmpty(searchText))
        {
            filtered = filtered.Where(m =>
                m.Content.Contains(searchText, StringComparison.OrdinalIgnoreCase) ||
                (m.Source?.Contains(searchText, StringComparison.OrdinalIgnoreCase) ?? false));
        }

        MemoryList.ItemsSource = filtered.ToList();
    }

    /// <summary>
    /// 통계 업데이트
    /// </summary>
    private void UpdateStatistics()
    {
        // 초기화 전에는 무시
        if (StatsText == null) return;

        var stats = _memoryService.GetStatistics();
        var hasFile = _memoryService.HasMemoryFile;

        if (hasFile)
        {
            StatsText.Text = $"총 {stats.Total}개 기억";
        }
        else
        {
            StatsText.Text = "MEMORY.md 없음 (추가 시 생성)";
        }
    }

    private static string GetTypeIcon(MemoryType type) => type switch
    {
        MemoryType.Architecture => "🏗️",
        MemoryType.Pattern => "🔄",
        MemoryType.Tool => "🔧",
        MemoryType.Gotcha => "⚠️",
        MemoryType.Goal => "🎯",
        MemoryType.Meta => "📁",
        _ => "•"
    };

    private static string GetTypeName(MemoryType type) => type switch
    {
        MemoryType.Architecture => "아키텍처",
        MemoryType.Pattern => "패턴",
        MemoryType.Tool => "도구",
        MemoryType.Gotcha => "주의사항",
        MemoryType.Goal => "목표",
        MemoryType.Meta => "메타",
        _ => "기타"
    };

    #region Event Handlers

    private void CloseButton_Click(object sender, RoutedEventArgs e)
    {
        CloseRequested?.Invoke(this, EventArgs.Empty);
    }

    private void SearchBox_KeyDown(object sender, KeyEventArgs e)
    {
        if (e.Key == Key.Enter)
        {
            ApplyFilter();
        }
    }

    private void SearchButton_Click(object sender, RoutedEventArgs e)
    {
        ApplyFilter();
    }

    private void TypeFilterCombo_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (TypeFilterCombo.SelectedItem is ComboBoxItem item)
        {
            var tag = item.Tag as string;
            if (string.IsNullOrEmpty(tag))
            {
                _currentTypeFilter = null;
            }
            else if (Enum.TryParse<MemoryType>(tag, out var type))
            {
                _currentTypeFilter = type;
            }
            ApplyFilter();
        }
    }

    private async void RefreshButton_Click(object sender, RoutedEventArgs e)
    {
        _memoryService.LoadFromFile();
        await RefreshMemories();
    }

    private void MemoryList_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        // 선택 시 추가 동작 (필요 시)
    }

    private async void DeleteMemory_Click(object sender, RoutedEventArgs e)
    {
        if (sender is Button button && button.Tag is int id)
        {
            var result = MessageBox.Show(
                "이 기억을 삭제하시겠습니까?",
                "기억 삭제",
                MessageBoxButton.YesNo,
                MessageBoxImage.Question);

            if (result == MessageBoxResult.Yes)
            {
                _memoryService.DeleteMemory(id);
                await RefreshMemories();
            }
        }
    }

    private async void AddButton_Click(object sender, RoutedEventArgs e)
    {
        // 작업 디렉토리가 설정되지 않았으면 경고
        if (_memoryService.MemoryFilePath == null)
        {
            MessageBox.Show(
                "먼저 폴더를 열어주세요.",
                "알림",
                MessageBoxButton.OK,
                MessageBoxImage.Information);
            return;
        }

        var dialog = new AddMemoryDialog();
        dialog.Owner = Window.GetWindow(this);

        if (dialog.ShowDialog() == true)
        {
            var entry = new MemoryEntry
            {
                Content = dialog.MemoryContent,
                Type = dialog.SelectedType,
                Importance = dialog.Importance,
                IsAutoGenerated = false
            };

            await _memoryService.AddMemory(entry);
            await RefreshMemories();
        }
    }

    private void ExportButton_Click(object sender, RoutedEventArgs e)
    {
        // MEMORY.md 파일 열기
        var filePath = _memoryService.MemoryFilePath;

        if (filePath == null)
        {
            MessageBox.Show(
                "먼저 폴더를 열어주세요.",
                "알림",
                MessageBoxButton.OK,
                MessageBoxImage.Information);
            return;
        }

        if (!File.Exists(filePath))
        {
            // 파일이 없으면 생성
            _memoryService.CreateMemoryFileIfNotExists();
        }

        try
        {
            // 기본 편집기로 열기
            Process.Start(new ProcessStartInfo
            {
                FileName = filePath,
                UseShellExecute = true
            });
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                $"파일을 열 수 없습니다: {ex.Message}",
                "오류",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
    }

    #endregion
}

/// <summary>
/// 메모리 표시용 아이템
/// </summary>
public class MemoryDisplayItem
{
    public int Id { get; set; }
    public string Content { get; set; } = string.Empty;
    public MemoryType Type { get; set; }
    public string TypeIcon { get; set; } = string.Empty;
    public string TypeName { get; set; } = string.Empty;
    public double Importance { get; set; }
    public string ImportanceText { get; set; } = string.Empty;
    public string? Source { get; set; }
    public bool HasSource { get; set; }
    public int AccessCount { get; set; }
    public string AccessInfo { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
    public bool IsAutoGenerated { get; set; }
}
