using System;
using System.Windows.Media;

namespace TermSnap.Models;

/// <summary>
/// AI 장기기억 항목 (claude-mem 스타일)
/// </summary>
public class MemoryEntry
{
    /// <summary>
    /// 고유 ID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 메모리 내용 (사실, 선호도, 경험 등)
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// 메모리 타입
    /// </summary>
    public MemoryType Type { get; set; } = MemoryType.Architecture;

    /// <summary>
    /// 메모리 소스 (대화에서 추출된 원문)
    /// </summary>
    public string? Source { get; set; }

    /// <summary>
    /// 관련 주제/컨텍스트
    /// </summary>
    public string? Context { get; set; }

    /// <summary>
    /// 중요도 (0.0 ~ 1.0)
    /// </summary>
    public double Importance { get; set; } = 0.5;

    /// <summary>
    /// 생성 시간
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.Now;

    /// <summary>
    /// 마지막 접근 시간
    /// </summary>
    public DateTime LastAccessedAt { get; set; } = DateTime.Now;

    /// <summary>
    /// 접근 횟수
    /// </summary>
    public int AccessCount { get; set; } = 0;

    /// <summary>
    /// 임베딩 벡터 (Base64 인코딩)
    /// </summary>
    public string? EmbeddingVector { get; set; }

    /// <summary>
    /// 활성화 여부
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// 자동 생성 여부 (AI가 대화에서 추출)
    /// </summary>
    public bool IsAutoGenerated { get; set; } = false;

    /// <summary>
    /// 세션 ID (어떤 세션에서 생성되었는지)
    /// </summary>
    public string? SessionId { get; set; }

    #region Display Properties

    /// <summary>
    /// 타입 아이콘 (UI 표시용) - 컨텍스트 트리 구조
    /// </summary>
    public string TypeIcon => Type switch
    {
        MemoryType.Architecture => "🏗️",
        MemoryType.Pattern => "🔄",
        MemoryType.Tool => "🔧",
        MemoryType.Gotcha => "⚠️",
        MemoryType.Goal => "🎯",
        MemoryType.Meta => "📁",
        _ => "📝"
    };

    /// <summary>
    /// 타입 이름 (UI 표시용) - 컨텍스트 트리 구조
    /// </summary>
    public string TypeName => Type switch
    {
        MemoryType.Architecture => "아키텍처",
        MemoryType.Pattern => "패턴",
        MemoryType.Tool => "도구",
        MemoryType.Gotcha => "주의사항",
        MemoryType.Goal => "목표",
        MemoryType.Meta => "메타",
        _ => "기타"
    };

    /// <summary>
    /// 중요도 텍스트 (UI 표시용)
    /// </summary>
    public string ImportanceText => Importance switch
    {
        >= 0.8 => "높음",
        >= 0.5 => "보통",
        _ => "낮음"
    };

    /// <summary>
    /// 소스 존재 여부
    /// </summary>
    public bool HasSource => !string.IsNullOrEmpty(Source);

    /// <summary>
    /// 컨텍스트 존재 여부
    /// </summary>
    public bool HasContext => !string.IsNullOrEmpty(Context);

    /// <summary>
    /// 접근 정보 (UI 표시용)
    /// </summary>
    public string AccessInfo => $"접근 {AccessCount}회";

    /// <summary>
    /// 생성일 표시 (UI용)
    /// </summary>
    public string CreatedAtDisplay => CreatedAt.ToString("yyyy-MM-dd");

    /// <summary>
    /// 타입별 테두리 색상 (claude-mem 스타일)
    /// </summary>
    public Brush TypeBorderBrush => Type switch
    {
        MemoryType.Architecture => new SolidColorBrush(Color.FromRgb(0x09, 0x69, 0xda)), // 파란색
        MemoryType.Pattern => new SolidColorBrush(Color.FromRgb(0x82, 0x50, 0xdf)),      // 보라색
        MemoryType.Tool => new SolidColorBrush(Color.FromRgb(0x1a, 0x7f, 0x37)),         // 초록색
        MemoryType.Gotcha => new SolidColorBrush(Color.FromRgb(0xcf, 0x22, 0x2e)),       // 빨간색
        MemoryType.Goal => new SolidColorBrush(Color.FromRgb(0xd4, 0xa7, 0x2c)),         // 금색
        MemoryType.Meta => new SolidColorBrush(Color.FromRgb(0x6e, 0x77, 0x81)),         // 회색
        _ => new SolidColorBrush(Color.FromRgb(0x6e, 0x77, 0x81))
    };

    /// <summary>
    /// 타입별 배경 색상 (claude-mem 스타일)
    /// </summary>
    public Brush TypeBackgroundBrush => Type switch
    {
        MemoryType.Architecture => new SolidColorBrush(Color.FromRgb(0xf0, 0xf6, 0xfb)), // 연한 파란
        MemoryType.Pattern => new SolidColorBrush(Color.FromRgb(0xf5, 0xf0, 0xff)),      // 연한 보라
        MemoryType.Tool => new SolidColorBrush(Color.FromRgb(0xf0, 0xff, 0xf4)),         // 연한 초록
        MemoryType.Gotcha => new SolidColorBrush(Color.FromRgb(0xff, 0xf5, 0xf5)),       // 연한 빨강
        MemoryType.Goal => new SolidColorBrush(Color.FromRgb(0xff, 0xfb, 0xf0)),         // 연한 금색
        MemoryType.Meta => new SolidColorBrush(Color.FromRgb(0xf6, 0xf8, 0xfa)),         // 연한 회색
        _ => new SolidColorBrush(Color.FromRgb(0xf6, 0xf8, 0xfa))
    };

    #endregion
}

/// <summary>
/// 메모리 타입 (컨텍스트 트리 구조)
/// </summary>
public enum MemoryType
{
    /// <summary>
    /// 아키텍처 - 설계 결정, 아키텍처 선택
    /// </summary>
    Architecture,

    /// <summary>
    /// 패턴 - 작업 패턴, 워크플로우
    /// </summary>
    Pattern,

    /// <summary>
    /// 도구 - MCP 서버, 외부 도구
    /// </summary>
    Tool,

    /// <summary>
    /// 주의사항 - 함정, gotchas
    /// </summary>
    Gotcha,

    /// <summary>
    /// 목표 - 프로젝트 목표
    /// </summary>
    Goal,

    /// <summary>
    /// 메타 - 프로젝트 정보
    /// </summary>
    Meta
}
