using System;

namespace TermSnap.Models;

/// <summary>
/// AI 장기기억 항목 (Mem0 스타일)
/// </summary>
public class MemoryEntry
{
    /// <summary>
    /// 고유 ID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 메모리 내용 (사실, 선호도, 경험 등)
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// 메모리 타입
    /// </summary>
    public MemoryType Type { get; set; } = MemoryType.Fact;

    /// <summary>
    /// 메모리 소스 (대화에서 추출된 원문)
    /// </summary>
    public string? Source { get; set; }

    /// <summary>
    /// 관련 주제/컨텍스트
    /// </summary>
    public string? Context { get; set; }

    /// <summary>
    /// 중요도 (0.0 ~ 1.0)
    /// </summary>
    public double Importance { get; set; } = 0.5;

    /// <summary>
    /// 생성 시간
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.Now;

    /// <summary>
    /// 마지막 접근 시간
    /// </summary>
    public DateTime LastAccessedAt { get; set; } = DateTime.Now;

    /// <summary>
    /// 접근 횟수
    /// </summary>
    public int AccessCount { get; set; } = 0;

    /// <summary>
    /// 임베딩 벡터 (Base64 인코딩)
    /// </summary>
    public string? EmbeddingVector { get; set; }

    /// <summary>
    /// 활성화 여부
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// 자동 생성 여부 (AI가 대화에서 추출)
    /// </summary>
    public bool IsAutoGenerated { get; set; } = false;

    /// <summary>
    /// 세션 ID (어떤 세션에서 생성되었는지)
    /// </summary>
    public string? SessionId { get; set; }
}

/// <summary>
/// 메모리 타입
/// </summary>
public enum MemoryType
{
    /// <summary>
    /// 사실 (이름, 직업, 위치 등)
    /// </summary>
    Fact,

    /// <summary>
    /// 선호도 (좋아하는 것, 싫어하는 것)
    /// </summary>
    Preference,

    /// <summary>
    /// 경험 (이전에 했던 것)
    /// </summary>
    Experience,

    /// <summary>
    /// 프로젝트 정보
    /// </summary>
    Project,

    /// <summary>
    /// 기술 스택
    /// </summary>
    TechStack,

    /// <summary>
    /// 작업 패턴
    /// </summary>
    WorkPattern,

    /// <summary>
    /// 커스텀 지침
    /// </summary>
    Instruction,

    /// <summary>
    /// 학습된 교훈 (오류/실수 패턴)
    /// </summary>
    Lesson
}
